covid_api_host: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/
covid_workpoint_api_host: https://covid19-cdn.workpointnews.com/api/
covid_cases_thai_host: https://spreadsheets.google.com/feeds/list/1X1bXChhDm0ymr7pZ5g7uomlEFJqvao5nfHqEY4RWzlc/1/public/values?alt=json
covid_hospitals_host: https://spreadsheets.google.com/feeds/list/1X1bXChhDm0ymr7pZ5g7uomlEFJqvao5nfHqEY4RWzlc/4/public/values?alt=json
covid_safe_zone_host: https://spreadsheets.google.com/feeds/list/1X1bXChhDm0ymr7pZ5g7uomlEFJqvao5nfHqEY4RWzlc/5/public/values?alt=json
covid_thai_summary_host: https://spreadsheets.google.com/feeds/list/1X1bXChhDm0ymr7pZ5g7uomlEFJqvao5nfHqEY4RWzlc/8/public/values?alt=json
covid_hospital_labs_host: https://map.longdo.com/covid19-hospital/hospital-lab-covid19.json
covid_thai_ddc_host: https://ddc.moph.go.th/viralpneumonia/eng/
line_notify_token: E02Wl2DnPrbktHGtCadBzh2rBY5BjBw6YMHpSxV7ivG
line_channel_id: '1653946879'
line_channel_secret: cea83883ecfcdc8ba8887cfe4bdb7d8b
line_channel_token: v+zlCsRn9DJPCjYzBooWfN9Hko3zymHqNG7+V8cBCtcNcr9+WIaN4vIA1+EztWnVsVmma52BvVIWjNE6yTtomdEaKggvkD2pV3KAU38zbY64h+LXpGiKfikwiD5vI+7aOel2PSwZ6S8WevgvJBh1zAdB04t89/1O/w1cDnyilFU=
dialogflow_client_access_token: 286cf35508e64489b0c025d767e28e83
google_api_key: AIzaSyByaaldtl6PxcbsTkdwbcsbknjWQenVx9Y
google_key_id: 239405853de26ce778479fdeb131a5d2505fe183

production:
  covid_api_host: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/
  covid_workpoint_api_host: https://covid19-cdn.workpointnews.com/api/
  covid_cases_thai_host: https://spreadsheets.google.com/feeds/list/1X1bXChhDm0ymr7pZ5g7uomlEFJqvao5nfHqEY4RWzlc/1/public/values?alt=json
  covid_hospitals_host: https://spreadsheets.google.com/feeds/list/1X1bXChhDm0ymr7pZ5g7uomlEFJqvao5nfHqEY4RWzlc/4/public/values?alt=json
  covid_safe_zone_host: https://spreadsheets.google.com/feeds/list/1X1bXChhDm0ymr7pZ5g7uomlEFJqvao5nfHqEY4RWzlc/5/public/values?alt=json
  covid_thai_summary_host: https://spreadsheets.google.com/feeds/list/1X1bXChhDm0ymr7pZ5g7uomlEFJqvao5nfHqEY4RWzlc/8/public/values?alt=json
  covid_hospital_labs_host: https://map.longdo.com/covid19-hospital/hospital-lab-covid19.json
  covid_thai_ddc_host: https://ddc.moph.go.th/viralpneumonia/eng/
  line_notify_token: E02Wl2DnPrbktHGtCadBzh2rBY5BjBw6YMHpSxV7ivG
  line_channel_id: '1653946879'
  line_channel_secret: cea83883ecfcdc8ba8887cfe4bdb7d8b
  line_channel_token: v+zlCsRn9DJPCjYzBooWfN9Hko3zymHqNG7+V8cBCtcNcr9+WIaN4vIA1+EztWnVsVmma52BvVIWjNE6yTtomdEaKggvkD2pV3KAU38zbY64h+LXpGiKfikwiD5vI+7aOel2PSwZ6S8WevgvJBh1zAdB04t89/1O/w1cDnyilFU=
  dialogflow_client_access_token: 286cf35508e64489b0c025d767e28e83
  google_api_key: AIzaSyByaaldtl6PxcbsTkdwbcsbknjWQenVx9Y
  google_key_id: 239405853de26ce778479fdeb131a5d2505fe183
